# Generated by Django 4.0.6 on 2022-12-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=15)),
                ('exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salaryinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('basic', models.IntegerField()),
                ('lop', models.IntegerField()),
                ('bonus', models.IntegerField()),
            ],
        ),
    ]
